services:
  api:
    container_name: evolution_api
    image: atendai/evolution-api:homolog
    restart: always
    depends_on:
      - redis
      - postgres
    ports:
      - 8080:8080
    volumes:
      - evolution_instances:/evolution/instances
    networks:
      - evolution-net
    environment:
      - SERVER_TYPE=${SERVER_TYPE:-http}
      - SERVER_PORT=${SERVER_PORT:-8080}
      - SERVICE_FQDN_API
      - SERVER_URL=${SERVICE_URL_API:-http://localhost:8080}
      - CORS_ORIGIN=${CORS_ORIGIN:-*}
      - CORS_METHODS=${CORS_METHODS:-GET,POST,PUT,DELETE}
      - CORS_CREDENTIALS=${CORS_CREDENTIALS:-true}
      - LOG_LEVEL=${LOG_LEVEL:-ERROR,WARN,DEBUG,INFO,LOG,VERBOSE,DARK,WEBHOOKS,WEBSOCKET}
      - LOG_COLOR=${LOG_COLOR:-true}
      - LOG_BAILEYS=${LOG_BAILEYS:-error}
      - EVENT_EMITTER_MAX_LISTENERS=${EVENT_EMITTER_MAX_LISTENERS:-50}
      - DEL_INSTANCE=${DEL_INSTANCE:-false}
      - DATABASE_PROVIDER=${DATABASE_PROVIDER:-postgresql}
      - DATABASE_CONNECTION_URI=${DATABASE_CONNECTION_URI:-postgresql://user:pass@postgres:5432/evolution?schema=public}
      - DATABASE_CONNECTION_CLIENT_NAME=${DATABASE_CONNECTION_CLIENT_NAME:-evolution_exchange}
      - DATABASE_SAVE_DATA_INSTANCE=${DATABASE_SAVE_DATA_INSTANCE:-true}
      - DATABASE_SAVE_DATA_NEW_MESSAGE=${DATABASE_SAVE_DATA_NEW_MESSAGE:-true}
      - DATABASE_SAVE_MESSAGE_UPDATE=${DATABASE_SAVE_MESSAGE_UPDATE:-true}
      - DATABASE_SAVE_DATA_CONTACTS=${DATABASE_SAVE_DATA_CONTACTS:-true}
      - DATABASE_SAVE_DATA_CHATS=${DATABASE_SAVE_DATA_CHATS:-true}
      - DATABASE_SAVE_DATA_LABELS=${DATABASE_SAVE_DATA_LABELS:-true}
      - DATABASE_SAVE_DATA_HISTORIC=${DATABASE_SAVE_DATA_HISTORIC:-true}
      - DATABASE_SAVE_IS_ON_WHATSAPP=${DATABASE_SAVE_IS_ON_WHATSAPP:-true}
      - DATABASE_SAVE_IS_ON_WHATSAPP_DAYS=${DATABASE_SAVE_IS_ON_WHATSAPP_DAYS:-7}
      - DATABASE_DELETE_MESSAGE=${DATABASE_DELETE_MESSAGE:-true}
      # Variabili di autenticazione
      - AUTHENTICATION_API_KEY=${AUTHENTICATION_API_KEY:-429683C4C977415CAAFCCE10F7D57E11}
      - AUTHENTICATION_EXPOSE_IN_FETCH_INSTANCES=${AUTHENTICATION_EXPOSE_IN_FETCH_INSTANCES:-true}
      - LANGUAGE=${LANGUAGE:-en}
      # Variabili per il convertitore audio (opzionali)
      - API_AUDIO_CONVERTER=${API_AUDIO_CONVERTER:-}
      - API_AUDIO_CONVERTER_KEY=${API_AUDIO_CONVERTER_KEY:-}
      # Variabili per il proxy globale (opzionali)
      - PROXY_HOST=${PROXY_HOST:-}
      - PROXY_PORT=${PROXY_PORT:-80}
      - PROXY_PROTOCOL=${PROXY_PROTOCOL:-http}
      - PROXY_USERNAME=${PROXY_USERNAME:-}
      - PROXY_PASSWORD=${PROXY_PASSWORD:-}
    expose:
      - 8080

  redis:
    image: redis:latest
    networks:
      - evolution-net
    container_name: redis
    command: >
      redis-server --port 6379 --appendonly yes
    volumes:
      - evolution_redis:/data
    ports:
      - 6379:6379

  postgres:
    container_name: postgres
    image: postgres:15
    networks:
      - evolution-net
    command: ["postgres", "-c", "max_connections=1000", "-c", "listen_addresses=*"]
    restart: always
    ports:
      - 5432:5432
    environment:
      - POSTGRES_USER=${POSTGRES_USER:-user}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD:-pass}
      - POSTGRES_DB=${POSTGRES_DB:-evolution}
      - POSTGRES_HOST_AUTH_METHOD=${POSTGRES_HOST_AUTH_METHOD:-trust}
    volumes:
      - postgres_data:/var/lib/postgresql/data
    expose:
      - 5432

volumes:
  evolution_instances:
  evolution_redis:
  postgres_data:


networks:
  evolution-net:
    name: evolution-net
    driver: bridge
