services:
  api:
    container_name: evolution_api
    image: atendai/evolution-api:homolog
    restart: always
    depends_on:
      - redis
      - postgres
    ports:
      - 8081:8080
    volumes:
      - evolution_instances:/evolution/instances
    networks:
      - evolution-net
    environment:
      # Configurazione server
      - SERVER_TYPE=${SERVER_TYPE:-http}
      - SERVER_PORT=${SERVER_PORT:-8080}
      - SERVICE_FQDN_API
      - SERVER_URL=${SERVICE_URL_API:-http://localhost:8080}
      - SENTRY_DSN=${SENTRY_DSN:-}
      
      # Configurazione CORS
      - CORS_ORIGIN=${CORS_ORIGIN:-*}
      - CORS_METHODS=${CORS_METHODS:-GET,POST,PUT,DELETE}
      - CORS_CREDENTIALS=${CORS_CREDENTIALS:-true}
      
      # Configurazione log
      - LOG_LEVEL=${LOG_LEVEL:-ERROR,WARN,DEBUG,INFO,LOG,VERBOSE,DARK,WEBHOOKS,WEBSOCKET}
      - LOG_COLOR=${LOG_COLOR:-true}
      - LOG_BAILEYS=${LOG_BAILEYS:-error}
      
      # Configurazione eventi
      - EVENT_EMITTER_MAX_LISTENERS=${EVENT_EMITTER_MAX_LISTENERS:-50}
      - DEL_INSTANCE=${DEL_INSTANCE:-false}
      
      # Configurazione database
      - DATABASE_PROVIDER=${DATABASE_PROVIDER:-postgresql}
      - DATABASE_CONNECTION_URI=${DATABASE_CONNECTION_URI:-postgresql://user:pass@postgres:5432/evolution?schema=public}
      - DATABASE_CONNECTION_CLIENT_NAME=${DATABASE_CONNECTION_CLIENT_NAME:-evolution_exchange}
      - DATABASE_SAVE_DATA_INSTANCE=${DATABASE_SAVE_DATA_INSTANCE:-true}
      - DATABASE_SAVE_DATA_NEW_MESSAGE=${DATABASE_SAVE_DATA_NEW_MESSAGE:-true}
      - DATABASE_SAVE_MESSAGE_UPDATE=${DATABASE_SAVE_MESSAGE_UPDATE:-true}
      - DATABASE_SAVE_DATA_CONTACTS=${DATABASE_SAVE_DATA_CONTACTS:-true}
      - DATABASE_SAVE_DATA_CHATS=${DATABASE_SAVE_DATA_CHATS:-true}
      - DATABASE_SAVE_DATA_LABELS=${DATABASE_SAVE_DATA_LABELS:-true}
      - DATABASE_SAVE_DATA_HISTORIC=${DATABASE_SAVE_DATA_HISTORIC:-true}
      - DATABASE_SAVE_IS_ON_WHATSAPP=${DATABASE_SAVE_IS_ON_WHATSAPP:-true}
      - DATABASE_SAVE_IS_ON_WHATSAPP_DAYS=${DATABASE_SAVE_IS_ON_WHATSAPP_DAYS:-7}
      - DATABASE_DELETE_MESSAGE=${DATABASE_DELETE_MESSAGE:-true}
      
      # Configurazione RabbitMQ
      - RABBITMQ_ENABLED=${RABBITMQ_ENABLED:-false}
      - RABBITMQ_URI=${RABBITMQ_URI:-amqp://localhost}
      - RABBITMQ_EXCHANGE_NAME=${RABBITMQ_EXCHANGE_NAME:-evolution}
      - RABBITMQ_GLOBAL_ENABLED=${RABBITMQ_GLOBAL_ENABLED:-false}
      - RABBITMQ_PREFIX_KEY=${RABBITMQ_PREFIX_KEY:-evolution}
      - RABBITMQ_EVENTS_APPLICATION_STARTUP=${RABBITMQ_EVENTS_APPLICATION_STARTUP:-false}
      - RABBITMQ_EVENTS_INSTANCE_CREATE=${RABBITMQ_EVENTS_INSTANCE_CREATE:-false}
      - RABBITMQ_EVENTS_INSTANCE_DELETE=${RABBITMQ_EVENTS_INSTANCE_DELETE:-false}
      - RABBITMQ_EVENTS_QRCODE_UPDATED=${RABBITMQ_EVENTS_QRCODE_UPDATED:-false}
      - RABBITMQ_EVENTS_MESSAGES_SET=${RABBITMQ_EVENTS_MESSAGES_SET:-false}
      - RABBITMQ_EVENTS_MESSAGES_UPSERT=${RABBITMQ_EVENTS_MESSAGES_UPSERT:-false}
      - RABBITMQ_EVENTS_MESSAGES_EDITED=${RABBITMQ_EVENTS_MESSAGES_EDITED:-false}
      - RABBITMQ_EVENTS_MESSAGES_UPDATE=${RABBITMQ_EVENTS_MESSAGES_UPDATE:-false}
      - RABBITMQ_EVENTS_MESSAGES_DELETE=${RABBITMQ_EVENTS_MESSAGES_DELETE:-false}
      - RABBITMQ_EVENTS_SEND_MESSAGE=${RABBITMQ_EVENTS_SEND_MESSAGE:-false}
      - RABBITMQ_EVENTS_CONTACTS_SET=${RABBITMQ_EVENTS_CONTACTS_SET:-false}
      - RABBITMQ_EVENTS_CONTACTS_UPSERT=${RABBITMQ_EVENTS_CONTACTS_UPSERT:-false}
      - RABBITMQ_EVENTS_CONTACTS_UPDATE=${RABBITMQ_EVENTS_CONTACTS_UPDATE:-false}
      - RABBITMQ_EVENTS_PRESENCE_UPDATE=${RABBITMQ_EVENTS_PRESENCE_UPDATE:-false}
      - RABBITMQ_EVENTS_CHATS_SET=${RABBITMQ_EVENTS_CHATS_SET:-false}
      - RABBITMQ_EVENTS_CHATS_UPSERT=${RABBITMQ_EVENTS_CHATS_UPSERT:-false}
      - RABBITMQ_EVENTS_CHATS_UPDATE=${RABBITMQ_EVENTS_CHATS_UPDATE:-false}
      - RABBITMQ_EVENTS_CHATS_DELETE=${RABBITMQ_EVENTS_CHATS_DELETE:-false}
      - RABBITMQ_EVENTS_GROUPS_UPSERT=${RABBITMQ_EVENTS_GROUPS_UPSERT:-false}
      - RABBITMQ_EVENTS_GROUP_UPDATE=${RABBITMQ_EVENTS_GROUP_UPDATE:-false}
      - RABBITMQ_EVENTS_GROUP_PARTICIPANTS_UPDATE=${RABBITMQ_EVENTS_GROUP_PARTICIPANTS_UPDATE:-false}
      - RABBITMQ_EVENTS_CONNECTION_UPDATE=${RABBITMQ_EVENTS_CONNECTION_UPDATE:-false}
      - RABBITMQ_EVENTS_REMOVE_INSTANCE=${RABBITMQ_EVENTS_REMOVE_INSTANCE:-false}
      - RABBITMQ_EVENTS_LOGOUT_INSTANCE=${RABBITMQ_EVENTS_LOGOUT_INSTANCE:-false}
      - RABBITMQ_EVENTS_CALL=${RABBITMQ_EVENTS_CALL:-false}
      - RABBITMQ_EVENTS_TYPEBOT_START=${RABBITMQ_EVENTS_TYPEBOT_START:-false}
      - RABBITMQ_EVENTS_TYPEBOT_CHANGE_STATUS=${RABBITMQ_EVENTS_TYPEBOT_CHANGE_STATUS:-false}
      
      # Configurazione SQS
      - SQS_ENABLED=${SQS_ENABLED:-false}
      - SQS_ACCESS_KEY_ID=${SQS_ACCESS_KEY_ID:-}
      - SQS_SECRET_ACCESS_KEY=${SQS_SECRET_ACCESS_KEY:-}
      - SQS_ACCOUNT_ID=${SQS_ACCOUNT_ID:-}
      - SQS_REGION=${SQS_REGION:-}
      
      # Configurazione WebSocket
      - WEBSOCKET_ENABLED=${WEBSOCKET_ENABLED:-false}
      - WEBSOCKET_GLOBAL_EVENTS=${WEBSOCKET_GLOBAL_EVENTS:-false}
      
      # Configurazione Pusher
      - PUSHER_ENABLED=${PUSHER_ENABLED:-false}
      - PUSHER_GLOBAL_ENABLED=${PUSHER_GLOBAL_ENABLED:-false}
      - PUSHER_GLOBAL_APP_ID=${PUSHER_GLOBAL_APP_ID:-}
      - PUSHER_GLOBAL_KEY=${PUSHER_GLOBAL_KEY:-}
      - PUSHER_GLOBAL_SECRET=${PUSHER_GLOBAL_SECRET:-}
      - PUSHER_GLOBAL_CLUSTER=${PUSHER_GLOBAL_CLUSTER:-}
      - PUSHER_GLOBAL_USE_TLS=${PUSHER_GLOBAL_USE_TLS:-true}
      - PUSHER_EVENTS_APPLICATION_STARTUP=${PUSHER_EVENTS_APPLICATION_STARTUP:-true}
      - PUSHER_EVENTS_QRCODE_UPDATED=${PUSHER_EVENTS_QRCODE_UPDATED:-true}
      - PUSHER_EVENTS_MESSAGES_SET=${PUSHER_EVENTS_MESSAGES_SET:-true}
      - PUSHER_EVENTS_MESSAGES_UPSERT=${PUSHER_EVENTS_MESSAGES_UPSERT:-true}
      - PUSHER_EVENTS_MESSAGES_EDITED=${PUSHER_EVENTS_MESSAGES_EDITED:-true}
      - PUSHER_EVENTS_MESSAGES_UPDATE=${PUSHER_EVENTS_MESSAGES_UPDATE:-true}
      - PUSHER_EVENTS_MESSAGES_DELETE=${PUSHER_EVENTS_MESSAGES_DELETE:-true}
      - PUSHER_EVENTS_SEND_MESSAGE=${PUSHER_EVENTS_SEND_MESSAGE:-true}
      - PUSHER_EVENTS_CONTACTS_SET=${PUSHER_EVENTS_CONTACTS_SET:-true}
      - PUSHER_EVENTS_CONTACTS_UPSERT=${PUSHER_EVENTS_CONTACTS_UPSERT:-true}
      - PUSHER_EVENTS_CONTACTS_UPDATE=${PUSHER_EVENTS_CONTACTS_UPDATE:-true}
      - PUSHER_EVENTS_PRESENCE_UPDATE=${PUSHER_EVENTS_PRESENCE_UPDATE:-true}
      - PUSHER_EVENTS_CHATS_SET=${PUSHER_EVENTS_CHATS_SET:-true}
      - PUSHER_EVENTS_CHATS_UPSERT=${PUSHER_EVENTS_CHATS_UPSERT:-true}
      - PUSHER_EVENTS_CHATS_UPDATE=${PUSHER_EVENTS_CHATS_UPDATE:-true}
      - PUSHER_EVENTS_CHATS_DELETE=${PUSHER_EVENTS_CHATS_DELETE:-true}
      - PUSHER_EVENTS_GROUPS_UPSERT=${PUSHER_EVENTS_GROUPS_UPSERT:-true}
      - PUSHER_EVENTS_GROUPS_UPDATE=${PUSHER_EVENTS_GROUPS_UPDATE:-true}
      - PUSHER_EVENTS_GROUP_PARTICIPANTS_UPDATE=${PUSHER_EVENTS_GROUP_PARTICIPANTS_UPDATE:-true}
      - PUSHER_EVENTS_CONNECTION_UPDATE=${PUSHER_EVENTS_CONNECTION_UPDATE:-true}
      - PUSHER_EVENTS_LABELS_EDIT=${PUSHER_EVENTS_LABELS_EDIT:-true}
      - PUSHER_EVENTS_LABELS_ASSOCIATION=${PUSHER_EVENTS_LABELS_ASSOCIATION:-true}
      - PUSHER_EVENTS_CALL=${PUSHER_EVENTS_CALL:-true}
      - PUSHER_EVENTS_TYPEBOT_START=${PUSHER_EVENTS_TYPEBOT_START:-false}
      - PUSHER_EVENTS_TYPEBOT_CHANGE_STATUS=${PUSHER_EVENTS_TYPEBOT_CHANGE_STATUS:-false}
      
      # Configurazione WhatsApp Business API
      - WA_BUSINESS_TOKEN_WEBHOOK=${WA_BUSINESS_TOKEN_WEBHOOK:-evolution}
      - WA_BUSINESS_URL=${WA_BUSINESS_URL:-https://graph.facebook.com}
      - WA_BUSINESS_VERSION=${WA_BUSINESS_VERSION:-v20.0}
      - WA_BUSINESS_LANGUAGE=${WA_BUSINESS_LANGUAGE:-en_US}
      
      # Configurazione Webhook
      - WEBHOOK_GLOBAL_ENABLED=${WEBHOOK_GLOBAL_ENABLED:-false}
      - WEBHOOK_GLOBAL_URL=${WEBHOOK_GLOBAL_URL:-}
      - WEBHOOK_GLOBAL_WEBHOOK_BY_EVENTS=${WEBHOOK_GLOBAL_WEBHOOK_BY_EVENTS:-false}
      - WEBHOOK_EVENTS_APPLICATION_STARTUP=${WEBHOOK_EVENTS_APPLICATION_STARTUP:-false}
      - WEBHOOK_EVENTS_QRCODE_UPDATED=${WEBHOOK_EVENTS_QRCODE_UPDATED:-true}
      - WEBHOOK_EVENTS_MESSAGES_SET=${WEBHOOK_EVENTS_MESSAGES_SET:-true}
      - WEBHOOK_EVENTS_MESSAGES_UPSERT=${WEBHOOK_EVENTS_MESSAGES_UPSERT:-true}
      - WEBHOOK_EVENTS_MESSAGES_EDITED=${WEBHOOK_EVENTS_MESSAGES_EDITED:-true}
      - WEBHOOK_EVENTS_MESSAGES_UPDATE=${WEBHOOK_EVENTS_MESSAGES_UPDATE:-true}
      - WEBHOOK_EVENTS_MESSAGES_DELETE=${WEBHOOK_EVENTS_MESSAGES_DELETE:-true}
      - WEBHOOK_EVENTS_SEND_MESSAGE=${WEBHOOK_EVENTS_SEND_MESSAGE:-true}
      - WEBHOOK_EVENTS_CONTACTS_SET=${WEBHOOK_EVENTS_CONTACTS_SET:-true}
      - WEBHOOK_EVENTS_CONTACTS_UPSERT=${WEBHOOK_EVENTS_CONTACTS_UPSERT:-true}
      - WEBHOOK_EVENTS_CONTACTS_UPDATE=${WEBHOOK_EVENTS_CONTACTS_UPDATE:-true}
      - WEBHOOK_EVENTS_PRESENCE_UPDATE=${WEBHOOK_EVENTS_PRESENCE_UPDATE:-true}
      - WEBHOOK_EVENTS_CHATS_SET=${WEBHOOK_EVENTS_CHATS_SET:-true}
      - WEBHOOK_EVENTS_CHATS_UPSERT=${WEBHOOK_EVENTS_CHATS_UPSERT:-true}
      - WEBHOOK_EVENTS_CHATS_UPDATE=${WEBHOOK_EVENTS_CHATS_UPDATE:-true}
      - WEBHOOK_EVENTS_CHATS_DELETE=${WEBHOOK_EVENTS_CHATS_DELETE:-true}
      - WEBHOOK_EVENTS_GROUPS_UPSERT=${WEBHOOK_EVENTS_GROUPS_UPSERT:-true}
      - WEBHOOK_EVENTS_GROUPS_UPDATE=${WEBHOOK_EVENTS_GROUPS_UPDATE:-true}
      - WEBHOOK_EVENTS_GROUP_PARTICIPANTS_UPDATE=${WEBHOOK_EVENTS_GROUP_PARTICIPANTS_UPDATE:-true}
      - WEBHOOK_EVENTS_CONNECTION_UPDATE=${WEBHOOK_EVENTS_CONNECTION_UPDATE:-true}
      - WEBHOOK_EVENTS_REMOVE_INSTANCE=${WEBHOOK_EVENTS_REMOVE_INSTANCE:-false}
      - WEBHOOK_EVENTS_LOGOUT_INSTANCE=${WEBHOOK_EVENTS_LOGOUT_INSTANCE:-false}
      - WEBHOOK_EVENTS_LABELS_EDIT=${WEBHOOK_EVENTS_LABELS_EDIT:-true}
      - WEBHOOK_EVENTS_LABELS_ASSOCIATION=${WEBHOOK_EVENTS_LABELS_ASSOCIATION:-true}
      - WEBHOOK_EVENTS_CALL=${WEBHOOK_EVENTS_CALL:-true}
      - WEBHOOK_EVENTS_TYPEBOT_START=${WEBHOOK_EVENTS_TYPEBOT_START:-false}
      - WEBHOOK_EVENTS_TYPEBOT_CHANGE_STATUS=${WEBHOOK_EVENTS_TYPEBOT_CHANGE_STATUS:-false}
      - WEBHOOK_EVENTS_ERRORS=${WEBHOOK_EVENTS_ERRORS:-false}
      - WEBHOOK_EVENTS_ERRORS_WEBHOOK=${WEBHOOK_EVENTS_ERRORS_WEBHOOK:-}
      
      # Configurazione sessione
      - CONFIG_SESSION_PHONE_CLIENT=${CONFIG_SESSION_PHONE_CLIENT:-Evolution API}
      - CONFIG_SESSION_PHONE_NAME=${CONFIG_SESSION_PHONE_NAME:-Chrome}
      - CONFIG_SESSION_PHONE_VERSION=${CONFIG_SESSION_PHONE_VERSION:-2.3000.1015901307}
      
      # Configurazione QRCode
      - QRCODE_LIMIT=${QRCODE_LIMIT:-30}
      - QRCODE_COLOR=${QRCODE_COLOR:-'#175197'}
      
      # Configurazione Typebot
      - TYPEBOT_ENABLED=${TYPEBOT_ENABLED:-false}
      - TYPEBOT_API_VERSION=${TYPEBOT_API_VERSION:-latest}
      
      # Configurazione Chatwoot
      - CHATWOOT_ENABLED=${CHATWOOT_ENABLED:-false}
      - CHATWOOT_MESSAGE_READ=${CHATWOOT_MESSAGE_READ:-true}
      - CHATWOOT_MESSAGE_DELETE=${CHATWOOT_MESSAGE_DELETE:-true}
      - CHATWOOT_BOT_CONTACT=${CHATWOOT_BOT_CONTACT:-true}
      - CHATWOOT_IMPORT_DATABASE_CONNECTION_URI=${CHATWOOT_IMPORT_DATABASE_CONNECTION_URI:-postgresql://user:passwprd@host:5432/chatwoot?sslmode=disable}
      - CHATWOOT_IMPORT_PLACEHOLDER_MEDIA_MESSAGE=${CHATWOOT_IMPORT_PLACEHOLDER_MEDIA_MESSAGE:-true}
      
      # Configurazione OpenAI e Dify
      - OPENAI_ENABLED=${OPENAI_ENABLED:-false}
      - DIFY_ENABLED=${DIFY_ENABLED:-false}
      
      # Configurazione Cache Redis
      - CACHE_REDIS_ENABLED=${CACHE_REDIS_ENABLED:-true}
      - CACHE_REDIS_URI=${CACHE_REDIS_URI:-redis://redis:6379/6}
      - CACHE_REDIS_TTL=${CACHE_REDIS_TTL:-604800}
      - CACHE_REDIS_PREFIX_KEY=${CACHE_REDIS_PREFIX_KEY:-evolution}
      - CACHE_REDIS_SAVE_INSTANCES=${CACHE_REDIS_SAVE_INSTANCES:-false}
      - CACHE_LOCAL_ENABLED=${CACHE_LOCAL_ENABLED:-false}
      
      # Configurazione Amazon S3
      - S3_ENABLED=${S3_ENABLED:-false}
      - S3_ACCESS_KEY=${S3_ACCESS_KEY:-}
      - S3_SECRET_KEY=${S3_SECRET_KEY:-}
      - S3_BUCKET=${S3_BUCKET:-evolution}
      - S3_PORT=${S3_PORT:-443}
      - S3_ENDPOINT=${S3_ENDPOINT:-s3.domain.com}
      - S3_REGION=${S3_REGION:-eu-west-3}
      - S3_USE_SSL=${S3_USE_SSL:-true}
      
      # Configurazione Audio Converter
      - API_AUDIO_CONVERTER=${API_AUDIO_CONVERTER:-}
      - API_AUDIO_CONVERTER_KEY=${API_AUDIO_CONVERTER_KEY:-}
      
      # Configurazione autenticazione
      - AUTHENTICATION_API_KEY=${AUTHENTICATION_API_KEY:-123456789}
      - AUTHENTICATION_EXPOSE_IN_FETCH_INSTANCES=${AUTHENTICATION_EXPOSE_IN_FETCH_INSTANCES:-true}
      - LANGUAGE=${LANGUAGE:-en}
      
      # Configurazione proxy
      - PROXY_HOST=${PROXY_HOST:-}
      - PROXY_PORT=${PROXY_PORT:-80}
      - PROXY_PROTOCOL=${PROXY_PROTOCOL:-http}
      - PROXY_USERNAME=${PROXY_USERNAME:-}
      - PROXY_PASSWORD=${PROXY_PASSWORD:-}
    expose:
      - 8080

  redis:
    image: redis:latest
    networks:
      - evolution-net
    container_name: redis
    command: >
      redis-server --port 6379 --appendonly yes
    volumes:
      - evolution_redis:/data
    ports:
      - 6379:6379

  postgres:
    container_name: postgres
    image: postgres:15
    networks:
      - evolution-net
    command: ["postgres", "-c", "max_connections=1000", "-c", "listen_addresses=*"]
    restart: always
    ports:
      - 5432:5432
    environment:
      - POSTGRES_USER=${POSTGRES_USER:-user}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD:-pass}
      - POSTGRES_DB=${POSTGRES_DB:-evolution}
      - POSTGRES_HOST_AUTH_METHOD=${POSTGRES_HOST_AUTH_METHOD:-trust}
    volumes:
      - postgres_data:/var/lib/postgresql/data
    expose:
      - 5432

volumes:
  evolution_instances:
  evolution_redis:
  postgres_data:


networks:
  evolution-net:
    name: evolution-net
    driver: bridge
